<a href="https://colab.research.google.com/github/professional12022007/Data-Science/blob/main/PANDAS2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [5]:
df=pd.read_csv("student.csv")

In [6]:
df.groupby('placement_status')['exam_score'].agg('mean')

placement_status
Not Placed    59.800954
Placed        91.998494
Name: exam_score, dtype: float64

In [10]:
df.groupby('placement_status')["study_hours"].mean()

placement_status
Not Placed    3.132029
Placed        6.552382
Name: study_hours, dtype: float64

In [13]:
df.groupby('exam_score')['study_hours'].sum()

exam_score
26.67         1
26.89         1
27.82         1
31.41         1
31.43         2
          ...
99.96         7
99.97         7
99.98        14
99.99        20
100.00    28438
Name: study_hours, Length: 3563, dtype: int64

In [14]:
def grade(x):
  if(x>=70):
    return 'A'
  elif(x>=60):
    return 'B'
  elif(x>=50):
    return 'C'
  else:
    return 'D'

In [15]:
df['grade']=df['exam_score'].apply(grade)
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,grade
0,7,56,8,7,10,62,100.00,Placed,A
1,4,69,5,3,8,56,100.00,Placed,A
2,11,60,7,6,10,45,100.00,Placed,A
3,8,99,9,8,4,55,90.17,Placed,A
4,5,52,8,6,8,40,78.82,Placed,A
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,B
9996,7,98,6,9,4,87,100.00,Placed,A
9997,10,44,8,5,10,37,95.94,Placed,A
9998,10,75,7,5,8,52,88.61,Placed,A
9999,2,70,6,11,16,52,78.96,Placed,A